sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t andrewastrachan92/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true andrewastrachan92/docker-react npm run test
